### ISSUE TITLE
Few stuff

### ISSUE THREAD

**Issue by ObelI** [dpc/rhex#10]
1. How to get out from Inventory ? ESC - Just write it in inventory 
2. How to use health potion from inventory
   I got :
   a - health potion a have pressed "a" and nothing hapend
3. When i died the game fall in the loop counting turns up
4. How to kill f****g rat :D
5. What examine is for ? 
6. One time the game has crap and I could go out of the map

**Comment by CryZe** [comment]
> How to use health potion from inventory I got : a - health potion a have pressed "a" and nothing hapend

You need to "equip" them. So you need to go into the equip menu and use them there. Pretty confusing. I'll try to fix that.
