### ISSUE TITLE
detect when started in non-256 colour mode and bottle out

### ISSUE THREAD

**Issue by tinyplasticgreyknight** [dpc/rhex#31]
Currently the game will take over the screen regardless, but you can't see anything clearly.  It's impossible to Ctrl-C or Ctrl-Z the game, you can only kill it from another terminal (you can also quit via the in-game commands if you have them memorised, but that isn't much help).

**Comment by dpc** [comment]
Yes.

This should be done before starting curses.

**Comment by GoldenBadger** [comment]
I would be happy to take this issue. Since it doesn't seem that `ncurses` has a built-in function for getting the number of terminal colours, I think a call to `tput colors` would be best.
